# Generated by Django 5.0.3 on 2024-03-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="assignee_id",
            new_name="assignee",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="author_id",
            new_name="author",
        ),
    ]
